wallace/custom.py

removes anonymization code in preparation for anonymize on export

Remove anonymization

---

wallace/custom.py

There's an issue with psiTurk where the worker_complete route is triggered
multiple times, reverting the status to 3 after we have already upgraded it
to a status >= 100. This commit changes the status to 3 only if it is not
already >= 100.

Overide psiTurk's worker_complete route

---

wallace/command_line.py
wallace/custom.py
wallace/models.py

An entry is added each time a notification arrives

Add Notification table

---

wallace/experiments.py

@thomasmorgan Can you take a look at this and see if it looks okay? Without this, it's impossible to run Wallace from outside a valid app because PsiTurk config's initialization looks for config.txt.

Fix CLI directory bug

---

examples/function-learning/static/js/task.js

This PR removes the first of two getInfo functions in tasks.js in the function-learning example code.  
It will fix issue #249

clean up duplicated getInfo function

---

wallace/command_line.py
wallace/custom.py
wallace/heroku/worker.py

Switch redis provider to redis cloud for better reliability and monitoring/logging.  Add debug logging for rq actions.

Change Redis Provider; Add Logging

---

wallace/heroku/requirements.txt

Specify Wallace version in requirements

---

wallace/custom.py

closes #286 .
Also fixes an error in a previous merge!

Bulletproof routes

---

wallace/custom.py
wallace/experiments.py

Pass participant

---

wallace/custom.py
wallace/experiments.py
wallace/models.py

the first 2 commits are duplicates of the other branch :-(

Participant json

---

tests/test_models.py
tests/test_networks.py
wallace/custom.py
wallace/experiments.py
wallace/models.py

mostly minor, but important changes are (1) class __init__ methods now check that their parents haven't failed, e.g. failed nodes can't make infos and (2) the node __init__ method now instructs the network to calculate_full(), this reduces the risk of the full property becoming out of sync with the actual network size.

Safer models

---

examples/bartlett1932/experiment.py
examples/function-learning/experiment.py
examples/mcmcp/experiment.py
wallace/__init__.py
wallace/custom.py
wallace/db.py
wallace/experiments.py
wallace/heroku/clock.py
wallace/heroku/psiturkapp.py
wallace/information.py
wallace/models.py
wallace/networks.py
wallace/nodes.py
wallace/processes.py
wallace/recruiters.py
wallace/transformations.py

comment and lint all files in the wallace/wallace directory. Finally, make 3 further changes to slightly better Wallace.

257 linted

---

examples/rogers/tests/tests.py
tests/test_networks.py
wallace/networks.py

This shifts networks into talking about nodes in general, as opposed to agents in particular. It makes networks a little more explicit than before and I don't think it breaks anything :-)

Count nodes

---

wallace/custom.py

adds a new route to get the json of a network

Get network route

---

examples/bartlett1932/experiment.py
examples/function-learning/experiment.py
tests/test_networks.py
wallace/networks.py

Dissociate Chain structure from transmission

---

examples/bartlett1932/templates/consent.html
examples/chatroom/templates/consent.html
examples/function-learning/templates/consent.html
examples/mcmcp/templates/consent.html

Redact consent forms

---

tests/test_networks.py
wallace/models.py

Give base Network add_node method

---

examples/chatroom/experiment.py
examples/mcmcp/experiment.py
wallace/experiments.py

Simplify create_network and _node

---

wallace/heroku/clock.py

update clock to use Wallace's participants table

---

wallace/custom.py

when we receive notifications they have finished
closes #369

assign participants end_times 

---

wallace/custom.py
wallace/heroku/clock.py

Fixes jul16

---

wallace/custom.py

fix assign_properties

---

wallace/custom.py
wallace/heroku/clock.py

makes some important changes to the clock code and the notifications route
Fixes a bug where participants who fail the attention check never have their status updated properly. Also makes sure the clock won't repeatedly pay participants a bonus.

Notification commit

---

examples/bartlett1932/static/scripts/questionnaire.js
examples/chatroom/static/scripts/questionnaire.js
examples/function-learning/static/scripts/questionnaire.js
examples/mcmcp/static/scripts/questionnaire.js
examples/rogers/static/scripts/questionnaire.js
wallace/custom.py
wallace/models.py

Add a __json__ method for Questions and rename a field

---

examples/bartlett1932/config.txt
examples/chatroom/config.txt
examples/function-learning/config.txt
examples/mcmcp/config.txt
examples/rogers/config.txt
requirements.txt
setup.cfg
setup.py
wallace/heroku/requirements.txt
wallace/version.py

Bumpversion

---

docs/Wallace-with-Anaconda.md

had wrong path for anaconda3 installs

updated readme

---

examples/function-learning/experiment.py
examples/rogers/tests/tests.py
tests/test_networks.py
wallace/models.py

Fix "direction=" vs. "connection=" issue

---

docs/Learning-to-use-Wallace.md
docs/Required-experimental-files.md
docs/Wallace-with-Anaconda.md

was still linking to nonexistent wiki pages, not good for anyone

Fixing doc links

---

docs/Developing-Wallace-(setup-guide).md

Mention conda before people have already started to try to install virtualenv or to brew install python.

Update conda install location

---

docs/Web-API.md

Update web api docs to be consistent with other rest api docs
